#!/bin/sh

/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

dmesg -n 1
 
cat << EOF

 Boot took $(cut -d' ' -f1 /proc/uptime) seconds

  __  __ _       _   _      _                  
 |  \/  (_)     (_) | |    (_)                 
 | \  / |_ _ __  _  | |     _ _ __  _   ___  __
 | |\/| | | '_ \| | | |    | | '_ \| | | \ \/ /
 | |  | | | | | | | | |____| | | | | |_| |>  < 
 |_|  |_|_|_| |_|_| |______|_|_| |_|\__,_/_/\_\
                                               
                                               

EOF
exec setsid cttyhack sh #https://busybox.net/FAQ.html#job_control
exec /bin/sh